### ISSUE TITLE
StartNavigationListner bug

### ISSUE THREAD

**Issue by aviadshiber** [aviadshiber/BionicEyeXamarin#1]
the application is crushing when trying to update the UI.
```
{Android.Util.AndroidRuntimeException: Only the original thread that created a view hierarchy can touch its views.
  at Java.Interop.JniEnvironment+InstanceMethods.CallVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00069] in <8acc8089c2ed40d08469fbaa6710a44c>:0 
  at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0002a] in <8acc8089c2ed40d08469fbaa6710a44c>:0 
  at Android.Views.View.set_Visibility (Android.Views.ViewStates value) [0x00022] in <6f8818d6ffa14f4bad6fb5f5d0f0e665>:0 
  at Xamarin.Forms.Platform.Android.ActivityIndicatorRenderer.UpdateVisibility () [0x00011] in D:\a\1\s\Xamarin.Forms.Platform.Android\Renderers\ActivityIndicatorRenderer.cs:72 
  at Xamarin.Forms.Platform.Android.ActivityIndicatorRenderer.OnElementPropertyChanged (System.Object sender, System.ComponentModel.PropertyChangedEventArgs e) [0x0001f] in D:\a\1\s\Xamarin.Forms.Platform.Android\Renderers\ActivityIndicatorRenderer.cs:49 
  at (wrapper delegate-invoke) <Module>.invoke_void_object_PropertyChangedEventArgs(object,System.ComponentModel.PropertyChangedEventArgs)
  at Xamarin.Forms.BindableObject.OnPropertyChanged (System.String propertyName) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:150 
  at Xamarin.Forms.Element.OnPropertyChanged (System.String propertyName) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\Element.cs:370 
  at Xamarin.Forms.BindableObject.SetValueActual (Xamarin.Forms.BindableProperty property, Xamarin.Forms.BindableObject+BindablePropertyContext context, System.Object value, System.Boolean currentlyApplying, Xamarin.Forms.Internals.SetValueFlags attributes, System.Boolean silent) [0x00114] in D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:623 
  at Xamarin.Forms.BindableObject.SetValueCore (Xamarin.Forms.BindableProperty property, System.Object value, Xamarin.Forms.Internals.SetValueFlags attributes, Xamarin.Forms.BindableObject+SetValuePrivateFlags privateAttributes) [0x0015b] in D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:417 
  at Xamarin.Forms.BindableObject.SetValue (Xamarin.Forms.BindableProperty property, System.Object value, System.Boolean fromStyle, System.Boolean checkAccess) [0x0003d] in D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:573 
  at Xamarin.Forms.BindableObject.SetValue (Xamarin.Forms.BindableProperty property, System.Object value) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\BindableObject.cs:99 
  at Xamarin.Forms.ActivityIndicator.set_IsRunning (System.Boolean value) [0x00000] in D:\a\1\s\Xamarin.Forms.Core\ActivityIndicator.cs:29 
  at BionicEyeXamarin.MainPage+<StartNavigationListner>d__20.MoveNext () [0x00043] in C:\Users\aviad\git\BionicEyeXamarin\BionicEyeXamarin\BionicEyeXamarin\MainPage.xaml.cs:224 
--- End of stack trace from previous location where exception was thrown ---
  at BionicEyeXamarin.MainPage+<>c__DisplayClass19_0+<<NavigateTo>b__0>d.MoveNext () [0x00064] in C:\Users\aviad\git\BionicEyeXamarin\BionicEyeXamarin\BionicEyeXamarin\MainPage.xaml.cs:205 
  --- End of managed Android.Util.AndroidRuntimeException stack trace ---
android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
	at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:7809)
	at android.view.ViewRootImpl.invalidateChildInParent(ViewRootImpl.java:1338)
	at android.view.ViewGroup.invalidateChild(ViewGroup.java:5446)
	at android.view.View.invalidateInternal(View.java:14749)
	at android.view.View.invalidate(View.java:14713)
	at android.view.View.setFlags(View.java:12542)
	at android.view.View.setVisibility(View.java:8611)
	at android.widget.ProgressBar.setVisibility(ProgressBar.java:1777)
}
```

**Comment by aviadshiber** [comment]
fixed it , the problem was I forgot to use Device.BeginInvokeOnMainThread when updating the view
